[[language]]
name = "c"
language-servers = ["clangd"]
formatter = { command = "clang-format" }
auto-format = true

[[language]]
name = "cpp"
language-servers = ["clangd"]
formatter = { command = "clang-format" }
auto-format = true

# 需要单独安装 deno
[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
environment = { NO_COLOR = "true" }

[language-server.deno-lsp.config.deno]
enable = true
lint = true

[language-server.deno-lsp.config.deno.suggest.imports]
autoDiscover = true

[language-server.deno-lsp.config.deno.suggest.imports.hosts]
"https://jsr.io" = true

[[language]]
name = "javascript"
language-servers = ["deno-lsp"]
formatter = { command = "deno", args = ["fmt", "-", "--ext=js"] }
auto-format = true

[[language]]
name = "jsx"
language-servers = ["deno-lsp"]
formatter = { command = "deno", args = ["fmt", "-", "--ext=jsx"] }
auto-format = true

[[language]]
name = "typescript"
language-servers = ["deno-lsp"]
formatter = { command = "deno", args = ["fmt", "-", "--ext=ts"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = ["deno-lsp"]
formatter = { command = "deno", args = ["fmt", "-", "--ext=tsx"] }
auto-format = true

# 安装命令
# deno install -fAg --minimum-dependency-age=0 -n vscode-html-language-server \
#   "jsr:@qarks/vscode-language-servers/html"
[[language]]
name = "html"
language-servers = ["vscode-html-language-server"]
formatter = { command = "deno", args = ["fmt", "-", "--ext=html"] }
auto-format = true

# 安装命令
# deno install -fAg --minimum-dependency-age=0 -n vscode-css-language-server \
#   "jsr:@qarks/vscode-language-servers/css"
[[language]]
name = "css"
language-servers = ["vscode-css-language-server"]
formatter = { command = "deno", args = ["fmt", "-", "--ext=css"] }
auto-format = true

[[language]]
name = "python"
language-servers = ["ty", "ruff"]
formatter = { command = "ruff", args = ["format", "-"] }
auto-format = true

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
formatter = { command = "rustfmt" }
auto-format = true

# 需要单独安装 tinymist
[language-server.tinymist]
command = "tinymist"

[language-server.tinymist.config]
fontPaths = ["fonts"]
lint = { enabled = true }

[[language]]
name = "typst"
language-servers = ["tinymist"]
rulers = [97, 129]
auto-format = true

[[language]]
name = "markdown"
formatter = { command = "deno", args = [
  "fmt",
  "-",
  "--ext=md",
  "--prose-wrap=preserve",
] }
rulers = [97, 129]
auto-format = true

# 需要使用 deno install -fAg bash-language-server 安装
# 并且需要安装 shfmt 与 shellcheck
[[language]]
name = "bash"
language-servers = ["bash-language-server"]
formatter = { command = "shfmt", args = ["--indent=2"] }
auto-format = true

# 需要使用 cargo install --lock --features lsp taplo-cli 来安装
[[language]]
name = "toml"
language-servers = ["taplo"]
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true

# 安装命令
# deno install -fAg --minimum-dependency-age=0 -n vscode-json-language-server \
#   "jsr:@qarks/vscode-language-servers/json"
[[language]]
name = "json"
language-servers = ["vscode-json-language-server"]
formatter = { command = "deno", args = ["fmt", "-", "--ext=json"] }
auto-format = true

# 安装命令
# deno install -fAg --minimum-dependency-age=0 -n vscode-json-language-server \
#   "jsr:@qarks/vscode-language-servers/json"
[[language]]
name = "jsonc"
language-servers = ["vscode-json-language-server"]
formatter = { command = "deno", args = ["fmt", "-", "--ext=jsonc"] }
auto-format = true

[[language]]
name = "yaml"
formatter = { command = "deno", args = ["fmt", "-", "--ext=yaml"] }
auto-format = true
