#! /usr/bin/env bash

#mysql history
export MYSQL_HISTFILE="$XDG_STATE_HOME"/mysql_history

# path
allPath="$HOME/.local/bin"
allPath+=":$HOME/.local/share/npm/bin"
allPath+=":$HOME/.local/share/cabal/bin"
allPath+=":$HOME/.local/share/cargo/bin"
allPath+=":$PATH"
export PATH="$allPath"

# ghcup-env
[ -f "/home/kands/.local/share/ghcup/env" ] && source "/home/kands/.local/share/ghcup/env"

systemctl --user import-environment PATH
