# zsh completion file for rebar3 (autogenerated by rebar3).

function _rebar3 {
  local -a commands

  _arguments \
   '(-s --help)'{-s,--help}'[rebar3 help]' \
   '(-v --version)'{-v,--version}'[Version of rebar3]' \
   "1: :->cmnds" \
   "*::arg:->args"

  case $state in
  cmnds)
    commands=(
      "do:Higher order provider for running multiple tasks in a sequence."
      "plugins:plugins namespace"
      "experimental:experimental namespace"
      "local:local namespace"
      "alias:List aliases'' definitions."
      "xref:Run cross reference analysis."
      "version:Print version for rebar and current Erlang."
      "upgrade:Upgrade dependencies."
      "update:Update package index."
      "unlock:Unlock dependencies."
      "tar:Tar archive of release built of project."
      "shell:Run shell with project apps and deps in path."
      "report:Provide a crash report to be sent to the rebar3 issues page."
      "relup:Create relup of releases."
      "release:Build release of project."
      "path:Print paths to build dirs in current profile."
      "pkgs:List information for a package."
      "new:Create new project from templates."
      "help:Display a list of tasks or help for a given task or subtask."
      "get-deps:Fetch dependencies."
      "eunit:Run EUnit Tests."
      "escriptize:Generate escript archive."
      "edoc:Generate documentation using edoc."
      "dialyzer:Run the Dialyzer analyzer on the project."
      "tree:Print dependency tree."
      "deps:List dependencies"
      "cover:Perform coverage analysis."
      "completion:Generate completion file for your shell."
      "compile:Compile apps .app.src and .erl files."
      "ct:Run Common Tests."
      "clean:Remove compiled beam files from apps."
      "as:Higher order provider for running multiple tasks in a sequence as a certain profiles."
    )
    _describe "command" commands
    ;;
  esac

  case "$words[1]" in
  do)
    _rebar3_do
    ;;
  plugins)
    _rebar3_plugins
    ;;
  experimental)
    _rebar3_experimental
    ;;
  local)
    _rebar3_local
    ;;
  alias)
    _rebar3_alias
    ;;
  xref)
    _rebar3_xref
    ;;
  version)
    _rebar3_version
    ;;
  upgrade)
    _rebar3_upgrade
    ;;
  update)
    _rebar3_update
    ;;
  unlock)
    _rebar3_unlock
    ;;
  tar)
    _rebar3_tar
    ;;
  shell)
    _rebar3_shell
    ;;
  report)
    _rebar3_report
    ;;
  relup)
    _rebar3_relup
    ;;
  release)
    _rebar3_release
    ;;
  path)
    _rebar3_path
    ;;
  pkgs)
    _rebar3_pkgs
    ;;
  new)
    _rebar3_new
    ;;
  help)
    _rebar3_help
    ;;
  get-deps)
    _rebar3_get-deps
    ;;
  eunit)
    _rebar3_eunit
    ;;
  escriptize)
    _rebar3_escriptize
    ;;
  edoc)
    _rebar3_edoc
    ;;
  dialyzer)
    _rebar3_dialyzer
    ;;
  tree)
    _rebar3_tree
    ;;
  deps)
    _rebar3_deps
    ;;
  cover)
    _rebar3_cover
    ;;
  completion)
    _rebar3_completion
    ;;
  compile)
    _rebar3_compile
    ;;
  ct)
    _rebar3_ct
    ;;
  clean)
    _rebar3_clean
    ;;
  as)
    _rebar3_as
    ;;
  esac
}

function _rebar3_do {
  local -a commands

  _arguments \
   "1: :->cmnds" \
   "*::arg:->args"

  case $state in
  cmnds)
    commands=(
      "plugins:plugins namespace"
      "experimental:experimental namespace"
      "local:local namespace"
      "alias:List aliases'' definitions."
      "xref:Run cross reference analysis."
      "version:Print version for rebar and current Erlang."
      "upgrade:Upgrade dependencies."
      "update:Update package index."
      "unlock:Unlock dependencies."
      "tar:Tar archive of release built of project."
      "shell:Run shell with project apps and deps in path."
      "report:Provide a crash report to be sent to the rebar3 issues page."
      "relup:Create relup of releases."
      "release:Build release of project."
      "path:Print paths to build dirs in current profile."
      "pkgs:List information for a package."
      "new:Create new project from templates."
      "help:Display a list of tasks or help for a given task or subtask."
      "get-deps:Fetch dependencies."
      "eunit:Run EUnit Tests."
      "escriptize:Generate escript archive."
      "edoc:Generate documentation using edoc."
      "dialyzer:Run the Dialyzer analyzer on the project."
      "tree:Print dependency tree."
      "deps:List dependencies"
      "cover:Perform coverage analysis."
      "completion:Generate completion file for your shell."
      "compile:Compile apps .app.src and .erl files."
      "ct:Run Common Tests."
      "clean:Remove compiled beam files from apps."
      "as:Higher order provider for running multiple tasks in a sequence as a certain profiles."
    )
    _describe "command" commands
    ;;
  esac

  case "$words[1]" in
  plugins)
    _rebar3_do_plugins
    ;;
  experimental)
    _rebar3_do_experimental
    ;;
  local)
    _rebar3_do_local
    ;;
  alias)
    _rebar3_do_alias
    ;;
  xref)
    _rebar3_do_xref
    ;;
  version)
    _rebar3_do_version
    ;;
  upgrade)
    _rebar3_do_upgrade
    ;;
  update)
    _rebar3_do_update
    ;;
  unlock)
    _rebar3_do_unlock
    ;;
  tar)
    _rebar3_do_tar
    ;;
  shell)
    _rebar3_do_shell
    ;;
  report)
    _rebar3_do_report
    ;;
  relup)
    _rebar3_do_relup
    ;;
  release)
    _rebar3_do_release
    ;;
  path)
    _rebar3_do_path
    ;;
  pkgs)
    _rebar3_do_pkgs
    ;;
  new)
    _rebar3_do_new
    ;;
  help)
    _rebar3_do_help
    ;;
  get-deps)
    _rebar3_do_get-deps
    ;;
  eunit)
    _rebar3_do_eunit
    ;;
  escriptize)
    _rebar3_do_escriptize
    ;;
  edoc)
    _rebar3_do_edoc
    ;;
  dialyzer)
    _rebar3_do_dialyzer
    ;;
  tree)
    _rebar3_do_tree
    ;;
  deps)
    _rebar3_do_deps
    ;;
  cover)
    _rebar3_do_cover
    ;;
  completion)
    _rebar3_do_completion
    ;;
  compile)
    _rebar3_do_compile
    ;;
  ct)
    _rebar3_do_ct
    ;;
  clean)
    _rebar3_do_clean
    ;;
  as)
    _rebar3_do_as
    ;;
  esac
}

function _rebar3_do_plugins {
  local -a commands

  _arguments \
   "1: :->cmnds" \
   "*::arg:->args"

  case $state in
  cmnds)
    commands=(
      "upgrade:Upgrade plugins"
      "list:List local and global plugins for this project"
    )
    _describe "command" commands
    ;;
  esac

  case "$words[1]" in
  upgrade)
    _rebar3_do_plugins_upgrade
    ;;
  list)
    _rebar3_do_plugins_list
    ;;
  esac
}

function _rebar3_do_plugins_upgrade {
  local -a commands

  _arguments \
   '1:Plugin to upgrade:' \
   '(-a --all)'{-a,--all}'[Upgrade all plugins.]' \


}

function _rebar3_do_plugins_list {
  local -a commands

   _message 'no more arguments'


}

function _rebar3_do_experimental {
  local -a commands

  _arguments \
   "1: :->cmnds" \
   "*::arg:->args"

  case $state in
  cmnds)
    commands=(
      "vendor:Turns dependencies into top-level apps"
      "manifest:Produce a project manifest"
    )
    _describe "command" commands
    ;;
  esac

  case "$words[1]" in
  vendor)
    _rebar3_do_experimental_vendor
    ;;
  manifest)
    _rebar3_do_experimental_manifest
    ;;
  esac
}

function _rebar3_do_experimental_vendor {
  local -a commands

   _message 'no more arguments'


}

function _rebar3_do_experimental_manifest {
  local -a commands

  _arguments \
   '(-f --format)'{-f,--format}'[Format for the manifest. Supported formats are: erlang, eetf \(Erlang External Binary Format\), json]' \
   '(-t --to)'{-t,--to}'[If specified, write the manifest to file]' \


}

function _rebar3_do_local {
  local -a commands

  _arguments \
   "1: :->cmnds" \
   "*::arg:->args"

  case $state in
  cmnds)
    commands=(
      "upgrade:Download latest rebar3 escript and extract."
      "install:Extract libs from rebar3 escript along with a run script."
    )
    _describe "command" commands
    ;;
  esac

  case "$words[1]" in
  upgrade)
    _rebar3_do_local_upgrade
    ;;
  install)
    _rebar3_do_local_install
    ;;
  esac
}

function _rebar3_do_local_upgrade {
  local -a commands

   _message 'no more arguments'


}

function _rebar3_do_local_install {
  local -a commands

   _message 'no more arguments'


}

function _rebar3_do_alias {
  local -a commands

   _message 'no more arguments'


}

function _rebar3_do_xref {
  local -a commands

   _message 'no more arguments'


}

function _rebar3_do_version {
  local -a commands

   _message 'no more arguments'


}

function _rebar3_do_upgrade {
  local -a commands

  _arguments \
   '(-a --all)'{-a,--all}'[Upgrade all dependencies.]' \
   '1:List of packages to upgrade.:' \


}

function _rebar3_do_update {
  local -a commands

   _message 'no more arguments'


}

function _rebar3_do_unlock {
  local -a commands

  _arguments \
   '(-a --all)'{-a,--all}'[Unlock all dependencies and remove the lock file.]' \
   '1:List of packages to unlock.:' \


}

function _rebar3_do_tar {
  local -a commands

  _arguments \
   '(--all)--all[If true runs the command against all configured  releases]' \
   '(-n --relname)'{-n,--relname}'[Specify the name for the release that will be generated]' \
   '(-v --relvsn)'{-v,--relvsn}'[Specify the version for the release]' \
   '(-u --upfrom)'{-u,--upfrom}'[Only valid with relup target, specify the release to upgrade from]' \
   '(-o --output-dir)'{-o,--output-dir}'[The output directory for the release. This is `./` by default.]' \
   '(-h --help)'{-h,--help}'[Print usage]' \
   '(-l --lib-dir)'{-l,--lib-dir}'[Additional dir that should be searched for OTP Apps]' \
   '(-d --dev-mode)'{-d,--dev-mode}'[Symlink the applications and configuration into the release instead of copying]' \
   '(-i --include-erts)'{-i,--include-erts}'[If true include a copy of erts used to build with, if a path include erts at that path. If false, do not include erts]' \
   '(-a --override)'{-a,--override}'[Provide an app name and a directory to override in the form <appname>:<app directory>]' \
   '(-c --config)'{-c,--config}'[The path to a config file]' \
   '(--overlay_vars)--overlay_vars[Path to a file of overlay variables]' \
   '(--vm_args)--vm_args[Path to a file to use for vm.args]' \
   '(--sys_config)--sys_config[Path to a file to use for sys.config]' \
   '(--system_libs)--system_libs[Boolean or path to dir of Erlang system libs]' \
   '(--version)--version[Print relx version]' \
   '(-r --root)'{-r,--root}'[The project root directory]' \
   '(-m --relnames)'{-m,--relnames}'[Like --all, but only build the releases in the list, e.g. --relnames rel1,rel2]' \


}

function _rebar3_do_shell {
  local -a commands

  _arguments \
   '(--config)--config[Path to the config file to use. Defaults to {shell, \[{config, File}\]} and then the relx sys.config file if not specified.]' \
   '(--name)--name[Gives a long name to the node.]' \
   '(--sname)--sname[Gives a short name to the node.]' \
   '(--setcookie)--setcookie[Sets the cookie if the node is distributed.]' \
   '(--script)--script[Path to an escript file to run before starting the project apps. Defaults to rebar.config {shell, \[{script_file, File}\]} if not specified.]' \
   '(--apps)--apps[A list of apps to boot before starting the shell. \(E.g. --apps app1,app2,app3\) Defaults to rebar.config {shell, \[{apps, Apps}\]} or relx apps if not specified.]' \
   '(-r --relname)'{-r,--relname}'[Name of the release to use as a template for the shell session.]' \
   '(-v --relvsn)'{-v,--relvsn}'[Version of the release to use for the shell session.]' \
   '(--start-clean)--start-clean[Cancel any applications in the ''apps'' list or release.]' \
   '(--env-file)--env-file[Path to file of os environment variables to setup before expanding vars in config files.]' \
   '(--user_drv_args)--user_drv_args[For versions of Erlang prior to 26, this option can be used to pass arguments to the user_drv start function for creating custom shells. Starting with Erlang 26, the arguments defined with this option are applied to the shell start_interactive function.]' \
   '(--eval)--eval[Erlang term\(s\) to execute after the apps have been started, but before the shell is presented to the user.]' \


}

function _rebar3_do_report {
  local -a commands

  _arguments \
   '1:Task to print details for.:' \


}

function _rebar3_do_relup {
  local -a commands

  _arguments \
   '(--all)--all[If true runs the command against all configured  releases]' \
   '(-n --relname)'{-n,--relname}'[Specify the name for the release that will be generated]' \
   '(-v --relvsn)'{-v,--relvsn}'[Specify the version for the release]' \
   '(-u --upfrom)'{-u,--upfrom}'[Only valid with relup target, specify the release to upgrade from]' \
   '(-o --output-dir)'{-o,--output-dir}'[The output directory for the release. This is `./` by default.]' \
   '(-h --help)'{-h,--help}'[Print usage]' \
   '(-l --lib-dir)'{-l,--lib-dir}'[Additional dir that should be searched for OTP Apps]' \
   '(-d --dev-mode)'{-d,--dev-mode}'[Symlink the applications and configuration into the release instead of copying]' \
   '(-i --include-erts)'{-i,--include-erts}'[If true include a copy of erts used to build with, if a path include erts at that path. If false, do not include erts]' \
   '(-a --override)'{-a,--override}'[Provide an app name and a directory to override in the form <appname>:<app directory>]' \
   '(-c --config)'{-c,--config}'[The path to a config file]' \
   '(--overlay_vars)--overlay_vars[Path to a file of overlay variables]' \
   '(--vm_args)--vm_args[Path to a file to use for vm.args]' \
   '(--sys_config)--sys_config[Path to a file to use for sys.config]' \
   '(--system_libs)--system_libs[Boolean or path to dir of Erlang system libs]' \
   '(--version)--version[Print relx version]' \
   '(-r --root)'{-r,--root}'[The project root directory]' \
   '(-m --relnames)'{-m,--relnames}'[Like --all, but only build the releases in the list, e.g. --relnames rel1,rel2]' \


}

function _rebar3_do_release {
  local -a commands

  _arguments \
   '(--all)--all[If true runs the command against all configured  releases]' \
   '(-n --relname)'{-n,--relname}'[Specify the name for the release that will be generated]' \
   '(-v --relvsn)'{-v,--relvsn}'[Specify the version for the release]' \
   '(-u --upfrom)'{-u,--upfrom}'[Only valid with relup target, specify the release to upgrade from]' \
   '(-o --output-dir)'{-o,--output-dir}'[The output directory for the release. This is `./` by default.]' \
   '(-h --help)'{-h,--help}'[Print usage]' \
   '(-l --lib-dir)'{-l,--lib-dir}'[Additional dir that should be searched for OTP Apps]' \
   '(-d --dev-mode)'{-d,--dev-mode}'[Symlink the applications and configuration into the release instead of copying]' \
   '(-i --include-erts)'{-i,--include-erts}'[If true include a copy of erts used to build with, if a path include erts at that path. If false, do not include erts]' \
   '(-a --override)'{-a,--override}'[Provide an app name and a directory to override in the form <appname>:<app directory>]' \
   '(-c --config)'{-c,--config}'[The path to a config file]' \
   '(--overlay_vars)--overlay_vars[Path to a file of overlay variables]' \
   '(--vm_args)--vm_args[Path to a file to use for vm.args]' \
   '(--sys_config)--sys_config[Path to a file to use for sys.config]' \
   '(--system_libs)--system_libs[Boolean or path to dir of Erlang system libs]' \
   '(--version)--version[Print relx version]' \
   '(-r --root)'{-r,--root}'[The project root directory]' \
   '(-m --relnames)'{-m,--relnames}'[Like --all, but only build the releases in the list, e.g. --relnames rel1,rel2]' \


}

function _rebar3_do_path {
  local -a commands

  _arguments \
   '(--app)--app[Comma separated list of applications to return paths for.]' \
   '(--base)--base[Return the `base'' path of the current profile.]' \
   '(--bin)--bin[Return the `bin'' path of the current profile.]' \
   '(--ebin)--ebin[Return all `ebin'' paths of the current profile''s applications.]' \
   '(--lib)--lib[Return the `lib'' path of the current profile.]' \
   '(--priv)--priv[Return the `priv'' path of the current profile''s applications.]' \
   '(-s --separator)'{-s,--separator}'[In case of multiple return paths, the separator character to use to join them.]' \
   '(--src)--src[Return the `src'' path of the current profile''s applications.]' \
   '(--rel)--rel[Return the `rel'' path of the current profile.]' \


}

function _rebar3_do_pkgs {
  local -a commands

  _arguments \
   '1:Package to fetch information for.:' \


}

function _rebar3_do_new {
  local -a commands

  _arguments \
   '(-f --force)'{-f,--force}'[overwrite existing files]' \


}

function _rebar3_do_help {
  local -a commands

  _arguments \
   '1:Task to print help for.:' \


}

function _rebar3_do_get-deps {
  local -a commands

   _message 'no more arguments'


}

function _rebar3_do_eunit {
  local -a commands

  _arguments \
   '(--app)--app[Comma separated list of application test suites to run. Equivalent to `\[{application, App}\]`.]' \
   '(--application)--application[Comma separated list of application test suites to run. Equivalent to `\[{application, App}\]`.]' \
   '(-c --cover)'{-c,--cover}'[Generate cover data. Defaults to false.]' \
   '(--cover_export_name)--cover_export_name[Base name of the coverdata file to write]' \
   '(-p --profile)'{-p,--profile}'[Show the slowest tests. Defaults to false.]' \
   '(-d --dir)'{-d,--dir}'[Comma separated list of dirs to load tests from. Equivalent to `\[{dir, Dir}\]`.]' \
   '(-f --file)'{-f,--file}'[Comma separated list of files to load tests from. Equivalent to `\[{file, File}\]`.]' \
   '(-m --module)'{-m,--module}'[Comma separated list of modules to load tests from. Equivalent to `\[{module, Module}\]`.]' \
   '(-t --test)'{-t,--test}'[Comma separated list of tests to run. The format is `Module:Func1+Func2`. Equivalent to `\[{test, Module, Function}\]`.]' \
   '(-s --suite)'{-s,--suite}'[Comma separated list of modules to load tests from. Equivalent to `\[{module, Module}\]`.]' \
   '(-g --generator)'{-g,--generator}'[Comma separated list of generators to load tests from. The format is `Module:Func1+Func2`. Equivalent to `\[{generator, Module, Function}\]`.]' \
   '(-v --verbose)'{-v,--verbose}'[Verbose output. Defaults to false.]' \
   '(--name)--name[Gives a long name to the node]' \
   '(--sname)--sname[Gives a short name to the node]' \
   '(--sys_config)--sys_config[List of application config files]' \
   '(--setcookie)--setcookie[Sets the cookie if the node is distributed]' \


}

function _rebar3_do_escriptize {
  local -a commands

  _arguments \
   '(-a --main-app)'{-a,--main-app}'[Specify the name of the application to build an escript for.]' \


}

function _rebar3_do_edoc {
  local -a commands

   _message 'no more arguments'


}

function _rebar3_do_dialyzer {
  local -a commands

  _arguments \
   '(-i --incremental)'{-i,--incremental}'[Enable incremental analysis mode. Default: false]' \
   '(-u --update-plt)'{-u,--update-plt}'[Enable updating the PLT. Default: true]' \
   '(-s --succ-typings)'{-s,--succ-typings}'[Enable success typing analysis. Default: true]' \
   '(--base-plt-location)--base-plt-location[The location of base PLT file, defaults to $HOME/.cache/rebar3]' \
   '(--plt-location)--plt-location[The location of the PLT file, defaults to the profile''s base directory]' \
   '(--plt-prefix)--plt-prefix[The prefix to the PLT file, defaults to "rebar3"]' \
   '(-a --app)'{-a,--app}'[Perform success typing analysis of a single application]' \
   '(--base-plt-prefix)--base-plt-prefix[The prefix to the base PLT file, defaults to "rebar3"]' \
   '(--statistics)--statistics[Print information about the progress of execution. Default: false]' \


}

function _rebar3_do_tree {
  local -a commands

  _arguments \
   '(-v --verbose)'{-v,--verbose}'[Print repo and branch/tag/ref for git and hg deps]' \


}

function _rebar3_do_deps {
  local -a commands

   _message 'no more arguments'


}

function _rebar3_do_cover {
  local -a commands

  _arguments \
   '(-r --reset)'{-r,--reset}'[Reset all coverdata.]' \
   '(-v --verbose)'{-v,--verbose}'[Print coverage analysis.]' \
   '(-m --min_coverage)'{-m,--min_coverage}'[Mandate a coverage percentage required to succeed \(0..100\)]' \


}

function _rebar3_do_completion {
  local -a commands

  _arguments \
   '(-a --aliases)'{-a,--aliases}'[Comma separated list of OS level aliases on which rebar3 completion will be triggered \(e.g. "rebar" or "r3"\).]' \
   '(-f --file)'{-f,--file}'[Completion file name. Relative to "_build/".]' \
   '(-s --shell)'{-s,--shell}'[Shell type, ''bash'' or ''zsh''.]' \


}

function _rebar3_do_compile {
  local -a commands

  _arguments \
   '(-d --deps_only)'{-d,--deps_only}'[Only compile dependencies, no project apps will be built.]' \


}

function _rebar3_do_ct {
  local -a commands

  _arguments \
   '(--dir)--dir[List of additional directories containing test suites]' \
   '(--suite)--suite[List of test suites to run]' \
   '(--group)--group[List of test groups to run]' \
   '(--case)--case[List of test cases to run]' \
   '(--label)--label[Test label]' \
   '(--config)--config[List of config files]' \
   '(--spec)--spec[List of test specifications]' \
   '(--join_specs)--join_specs[Merge all test specifications and perform a single test run]' \
   '(--allow_user_terms)--allow_user_terms[Allow user defined config values in config files]' \
   '(--logdir)--logdir[Log folder]' \
   '(--logopts)--logopts[Options for common test logging]' \
   '(--verbosity)--verbosity[Verbosity]' \
   '(-c --cover)'{-c,--cover}'[Generate cover data]' \
   '(--cover_export_name)--cover_export_name[Base name of the coverdata file to write]' \
   '(--repeat)--repeat[How often to repeat tests]' \
   '(--duration)--duration[Max runtime \(format: HHMMSS\)]' \
   '(--until)--until[Run until \(format: HHMMSS\)]' \
   '(--force_stop)--force_stop[Force stop on test timeout \(true | false | skip_rest\)]' \
   '(--basic_html)--basic_html[Show basic HTML]' \
   '(--stylesheet)--stylesheet[CSS stylesheet to apply to html output]' \
   '(--decrypt_key)--decrypt_key[Path to key for decrypting config]' \
   '(--decrypt_file)--decrypt_file[Path to file containing key for decrypting config]' \
   '(--abort_if_missing_suites)--abort_if_missing_suites[Abort if suites are missing]' \
   '(--multiply_timetraps)--multiply_timetraps[]' \
   '(--scale_timetraps)--scale_timetraps[Scale timetraps]' \
   '(--create_priv_dir)--create_priv_dir[Create priv dir \(auto_per_run | auto_per_tc | manual_per_tc\)]' \
   '(--include)--include[Directories containing additional include files]' \
   '(--readable)--readable[Shows test case names and only displays logs to shell on failures \(true | compact | false\)]' \
   '(-v --verbose)'{-v,--verbose}'[Verbose output]' \
   '(--name)--name[Gives a long name to the node]' \
   '(--sname)--sname[Gives a short name to the node]' \
   '(--setcookie)--setcookie[Sets the cookie if the node is distributed]' \
   '(--sys_config)--sys_config[List of application config files]' \
   '(--compile_only)--compile_only[Compile modules in the project with the test configuration but do not run the tests]' \
   '(--retry)--retry[Experimental feature. If any specification for previously failing test is found, runs them.]' \
   '(--fail_fast)--fail_fast[Experimental feature. If any test fails, the run is aborted. Since common test does not support this natively, we abort the rebar3 run on a failure. This May break CT''s disk logging and other rebar3 features.]' \


}

function _rebar3_do_clean {
  local -a commands

  _arguments \
   '(-a --all)'{-a,--all}'[Clean all apps include deps]' \
   '(--apps)--apps[Clean a specific list of apps or dependencies]' \
   '(-p --profile)'{-p,--profile}'[Clean under profile. Equivalent to `rebar3 as <profile> clean`]' \


}

function _rebar3_do_as {
  local -a commands

  _arguments \
   '1:Profiles to run as.:' \
   "1: :->cmnds" \
   "*::arg:->args"

  case $state in
  cmnds)
    commands=(
      "test:"
    )
    _describe "command" commands
    ;;
  esac

  case "$words[1]" in
  test)
    _rebar3_do_as_test
    ;;
  esac
}

function _rebar3_do_as_test {
  local -a commands

   _message 'no more arguments'


}

function _rebar3_plugins {
  local -a commands

  _arguments \
   "1: :->cmnds" \
   "*::arg:->args"

  case $state in
  cmnds)
    commands=(
      "upgrade:Upgrade plugins"
      "list:List local and global plugins for this project"
    )
    _describe "command" commands
    ;;
  esac

  case "$words[1]" in
  upgrade)
    _rebar3_plugins_upgrade
    ;;
  list)
    _rebar3_plugins_list
    ;;
  esac
}

function _rebar3_plugins_upgrade {
  local -a commands

  _arguments \
   '1:Plugin to upgrade:' \
   '(-a --all)'{-a,--all}'[Upgrade all plugins.]' \


}

function _rebar3_plugins_list {
  local -a commands

   _message 'no more arguments'


}

function _rebar3_experimental {
  local -a commands

  _arguments \
   "1: :->cmnds" \
   "*::arg:->args"

  case $state in
  cmnds)
    commands=(
      "vendor:Turns dependencies into top-level apps"
      "manifest:Produce a project manifest"
    )
    _describe "command" commands
    ;;
  esac

  case "$words[1]" in
  vendor)
    _rebar3_experimental_vendor
    ;;
  manifest)
    _rebar3_experimental_manifest
    ;;
  esac
}

function _rebar3_experimental_vendor {
  local -a commands

   _message 'no more arguments'


}

function _rebar3_experimental_manifest {
  local -a commands

  _arguments \
   '(-f --format)'{-f,--format}'[Format for the manifest. Supported formats are: erlang, eetf \(Erlang External Binary Format\), json]' \
   '(-t --to)'{-t,--to}'[If specified, write the manifest to file]' \


}

function _rebar3_local {
  local -a commands

  _arguments \
   "1: :->cmnds" \
   "*::arg:->args"

  case $state in
  cmnds)
    commands=(
      "upgrade:Download latest rebar3 escript and extract."
      "install:Extract libs from rebar3 escript along with a run script."
    )
    _describe "command" commands
    ;;
  esac

  case "$words[1]" in
  upgrade)
    _rebar3_local_upgrade
    ;;
  install)
    _rebar3_local_install
    ;;
  esac
}

function _rebar3_local_upgrade {
  local -a commands

   _message 'no more arguments'


}

function _rebar3_local_install {
  local -a commands

   _message 'no more arguments'


}

function _rebar3_alias {
  local -a commands

   _message 'no more arguments'


}

function _rebar3_xref {
  local -a commands

   _message 'no more arguments'


}

function _rebar3_version {
  local -a commands

   _message 'no more arguments'


}

function _rebar3_upgrade {
  local -a commands

  _arguments \
   '(-a --all)'{-a,--all}'[Upgrade all dependencies.]' \
   '1:List of packages to upgrade.:' \


}

function _rebar3_update {
  local -a commands

   _message 'no more arguments'


}

function _rebar3_unlock {
  local -a commands

  _arguments \
   '(-a --all)'{-a,--all}'[Unlock all dependencies and remove the lock file.]' \
   '1:List of packages to unlock.:' \


}

function _rebar3_tar {
  local -a commands

  _arguments \
   '(--all)--all[If true runs the command against all configured  releases]' \
   '(-n --relname)'{-n,--relname}'[Specify the name for the release that will be generated]' \
   '(-v --relvsn)'{-v,--relvsn}'[Specify the version for the release]' \
   '(-u --upfrom)'{-u,--upfrom}'[Only valid with relup target, specify the release to upgrade from]' \
   '(-o --output-dir)'{-o,--output-dir}'[The output directory for the release. This is `./` by default.]' \
   '(-h --help)'{-h,--help}'[Print usage]' \
   '(-l --lib-dir)'{-l,--lib-dir}'[Additional dir that should be searched for OTP Apps]' \
   '(-d --dev-mode)'{-d,--dev-mode}'[Symlink the applications and configuration into the release instead of copying]' \
   '(-i --include-erts)'{-i,--include-erts}'[If true include a copy of erts used to build with, if a path include erts at that path. If false, do not include erts]' \
   '(-a --override)'{-a,--override}'[Provide an app name and a directory to override in the form <appname>:<app directory>]' \
   '(-c --config)'{-c,--config}'[The path to a config file]' \
   '(--overlay_vars)--overlay_vars[Path to a file of overlay variables]' \
   '(--vm_args)--vm_args[Path to a file to use for vm.args]' \
   '(--sys_config)--sys_config[Path to a file to use for sys.config]' \
   '(--system_libs)--system_libs[Boolean or path to dir of Erlang system libs]' \
   '(--version)--version[Print relx version]' \
   '(-r --root)'{-r,--root}'[The project root directory]' \
   '(-m --relnames)'{-m,--relnames}'[Like --all, but only build the releases in the list, e.g. --relnames rel1,rel2]' \


}

function _rebar3_shell {
  local -a commands

  _arguments \
   '(--config)--config[Path to the config file to use. Defaults to {shell, \[{config, File}\]} and then the relx sys.config file if not specified.]' \
   '(--name)--name[Gives a long name to the node.]' \
   '(--sname)--sname[Gives a short name to the node.]' \
   '(--setcookie)--setcookie[Sets the cookie if the node is distributed.]' \
   '(--script)--script[Path to an escript file to run before starting the project apps. Defaults to rebar.config {shell, \[{script_file, File}\]} if not specified.]' \
   '(--apps)--apps[A list of apps to boot before starting the shell. \(E.g. --apps app1,app2,app3\) Defaults to rebar.config {shell, \[{apps, Apps}\]} or relx apps if not specified.]' \
   '(-r --relname)'{-r,--relname}'[Name of the release to use as a template for the shell session.]' \
   '(-v --relvsn)'{-v,--relvsn}'[Version of the release to use for the shell session.]' \
   '(--start-clean)--start-clean[Cancel any applications in the ''apps'' list or release.]' \
   '(--env-file)--env-file[Path to file of os environment variables to setup before expanding vars in config files.]' \
   '(--user_drv_args)--user_drv_args[For versions of Erlang prior to 26, this option can be used to pass arguments to the user_drv start function for creating custom shells. Starting with Erlang 26, the arguments defined with this option are applied to the shell start_interactive function.]' \
   '(--eval)--eval[Erlang term\(s\) to execute after the apps have been started, but before the shell is presented to the user.]' \


}

function _rebar3_report {
  local -a commands

  _arguments \
   '1:Task to print details for.:' \


}

function _rebar3_relup {
  local -a commands

  _arguments \
   '(--all)--all[If true runs the command against all configured  releases]' \
   '(-n --relname)'{-n,--relname}'[Specify the name for the release that will be generated]' \
   '(-v --relvsn)'{-v,--relvsn}'[Specify the version for the release]' \
   '(-u --upfrom)'{-u,--upfrom}'[Only valid with relup target, specify the release to upgrade from]' \
   '(-o --output-dir)'{-o,--output-dir}'[The output directory for the release. This is `./` by default.]' \
   '(-h --help)'{-h,--help}'[Print usage]' \
   '(-l --lib-dir)'{-l,--lib-dir}'[Additional dir that should be searched for OTP Apps]' \
   '(-d --dev-mode)'{-d,--dev-mode}'[Symlink the applications and configuration into the release instead of copying]' \
   '(-i --include-erts)'{-i,--include-erts}'[If true include a copy of erts used to build with, if a path include erts at that path. If false, do not include erts]' \
   '(-a --override)'{-a,--override}'[Provide an app name and a directory to override in the form <appname>:<app directory>]' \
   '(-c --config)'{-c,--config}'[The path to a config file]' \
   '(--overlay_vars)--overlay_vars[Path to a file of overlay variables]' \
   '(--vm_args)--vm_args[Path to a file to use for vm.args]' \
   '(--sys_config)--sys_config[Path to a file to use for sys.config]' \
   '(--system_libs)--system_libs[Boolean or path to dir of Erlang system libs]' \
   '(--version)--version[Print relx version]' \
   '(-r --root)'{-r,--root}'[The project root directory]' \
   '(-m --relnames)'{-m,--relnames}'[Like --all, but only build the releases in the list, e.g. --relnames rel1,rel2]' \


}

function _rebar3_release {
  local -a commands

  _arguments \
   '(--all)--all[If true runs the command against all configured  releases]' \
   '(-n --relname)'{-n,--relname}'[Specify the name for the release that will be generated]' \
   '(-v --relvsn)'{-v,--relvsn}'[Specify the version for the release]' \
   '(-u --upfrom)'{-u,--upfrom}'[Only valid with relup target, specify the release to upgrade from]' \
   '(-o --output-dir)'{-o,--output-dir}'[The output directory for the release. This is `./` by default.]' \
   '(-h --help)'{-h,--help}'[Print usage]' \
   '(-l --lib-dir)'{-l,--lib-dir}'[Additional dir that should be searched for OTP Apps]' \
   '(-d --dev-mode)'{-d,--dev-mode}'[Symlink the applications and configuration into the release instead of copying]' \
   '(-i --include-erts)'{-i,--include-erts}'[If true include a copy of erts used to build with, if a path include erts at that path. If false, do not include erts]' \
   '(-a --override)'{-a,--override}'[Provide an app name and a directory to override in the form <appname>:<app directory>]' \
   '(-c --config)'{-c,--config}'[The path to a config file]' \
   '(--overlay_vars)--overlay_vars[Path to a file of overlay variables]' \
   '(--vm_args)--vm_args[Path to a file to use for vm.args]' \
   '(--sys_config)--sys_config[Path to a file to use for sys.config]' \
   '(--system_libs)--system_libs[Boolean or path to dir of Erlang system libs]' \
   '(--version)--version[Print relx version]' \
   '(-r --root)'{-r,--root}'[The project root directory]' \
   '(-m --relnames)'{-m,--relnames}'[Like --all, but only build the releases in the list, e.g. --relnames rel1,rel2]' \


}

function _rebar3_path {
  local -a commands

  _arguments \
   '(--app)--app[Comma separated list of applications to return paths for.]' \
   '(--base)--base[Return the `base'' path of the current profile.]' \
   '(--bin)--bin[Return the `bin'' path of the current profile.]' \
   '(--ebin)--ebin[Return all `ebin'' paths of the current profile''s applications.]' \
   '(--lib)--lib[Return the `lib'' path of the current profile.]' \
   '(--priv)--priv[Return the `priv'' path of the current profile''s applications.]' \
   '(-s --separator)'{-s,--separator}'[In case of multiple return paths, the separator character to use to join them.]' \
   '(--src)--src[Return the `src'' path of the current profile''s applications.]' \
   '(--rel)--rel[Return the `rel'' path of the current profile.]' \


}

function _rebar3_pkgs {
  local -a commands

  _arguments \
   '1:Package to fetch information for.:' \


}

function _rebar3_new {
  local -a commands

  _arguments \
   '(-f --force)'{-f,--force}'[overwrite existing files]' \


}

function _rebar3_help {
  local -a commands

  _arguments \
   '1:Task to print help for.:' \


}

function _rebar3_get-deps {
  local -a commands

   _message 'no more arguments'


}

function _rebar3_eunit {
  local -a commands

  _arguments \
   '(--app)--app[Comma separated list of application test suites to run. Equivalent to `\[{application, App}\]`.]' \
   '(--application)--application[Comma separated list of application test suites to run. Equivalent to `\[{application, App}\]`.]' \
   '(-c --cover)'{-c,--cover}'[Generate cover data. Defaults to false.]' \
   '(--cover_export_name)--cover_export_name[Base name of the coverdata file to write]' \
   '(-p --profile)'{-p,--profile}'[Show the slowest tests. Defaults to false.]' \
   '(-d --dir)'{-d,--dir}'[Comma separated list of dirs to load tests from. Equivalent to `\[{dir, Dir}\]`.]' \
   '(-f --file)'{-f,--file}'[Comma separated list of files to load tests from. Equivalent to `\[{file, File}\]`.]' \
   '(-m --module)'{-m,--module}'[Comma separated list of modules to load tests from. Equivalent to `\[{module, Module}\]`.]' \
   '(-t --test)'{-t,--test}'[Comma separated list of tests to run. The format is `Module:Func1+Func2`. Equivalent to `\[{test, Module, Function}\]`.]' \
   '(-s --suite)'{-s,--suite}'[Comma separated list of modules to load tests from. Equivalent to `\[{module, Module}\]`.]' \
   '(-g --generator)'{-g,--generator}'[Comma separated list of generators to load tests from. The format is `Module:Func1+Func2`. Equivalent to `\[{generator, Module, Function}\]`.]' \
   '(-v --verbose)'{-v,--verbose}'[Verbose output. Defaults to false.]' \
   '(--name)--name[Gives a long name to the node]' \
   '(--sname)--sname[Gives a short name to the node]' \
   '(--sys_config)--sys_config[List of application config files]' \
   '(--setcookie)--setcookie[Sets the cookie if the node is distributed]' \


}

function _rebar3_escriptize {
  local -a commands

  _arguments \
   '(-a --main-app)'{-a,--main-app}'[Specify the name of the application to build an escript for.]' \


}

function _rebar3_edoc {
  local -a commands

   _message 'no more arguments'


}

function _rebar3_dialyzer {
  local -a commands

  _arguments \
   '(-i --incremental)'{-i,--incremental}'[Enable incremental analysis mode. Default: false]' \
   '(-u --update-plt)'{-u,--update-plt}'[Enable updating the PLT. Default: true]' \
   '(-s --succ-typings)'{-s,--succ-typings}'[Enable success typing analysis. Default: true]' \
   '(--base-plt-location)--base-plt-location[The location of base PLT file, defaults to $HOME/.cache/rebar3]' \
   '(--plt-location)--plt-location[The location of the PLT file, defaults to the profile''s base directory]' \
   '(--plt-prefix)--plt-prefix[The prefix to the PLT file, defaults to "rebar3"]' \
   '(-a --app)'{-a,--app}'[Perform success typing analysis of a single application]' \
   '(--base-plt-prefix)--base-plt-prefix[The prefix to the base PLT file, defaults to "rebar3"]' \
   '(--statistics)--statistics[Print information about the progress of execution. Default: false]' \


}

function _rebar3_tree {
  local -a commands

  _arguments \
   '(-v --verbose)'{-v,--verbose}'[Print repo and branch/tag/ref for git and hg deps]' \


}

function _rebar3_deps {
  local -a commands

   _message 'no more arguments'


}

function _rebar3_cover {
  local -a commands

  _arguments \
   '(-r --reset)'{-r,--reset}'[Reset all coverdata.]' \
   '(-v --verbose)'{-v,--verbose}'[Print coverage analysis.]' \
   '(-m --min_coverage)'{-m,--min_coverage}'[Mandate a coverage percentage required to succeed \(0..100\)]' \


}

function _rebar3_completion {
  local -a commands

  _arguments \
   '(-a --aliases)'{-a,--aliases}'[Comma separated list of OS level aliases on which rebar3 completion will be triggered \(e.g. "rebar" or "r3"\).]' \
   '(-f --file)'{-f,--file}'[Completion file name. Relative to "_build/".]' \
   '(-s --shell)'{-s,--shell}'[Shell type, ''bash'' or ''zsh''.]' \


}

function _rebar3_compile {
  local -a commands

  _arguments \
   '(-d --deps_only)'{-d,--deps_only}'[Only compile dependencies, no project apps will be built.]' \


}

function _rebar3_ct {
  local -a commands

  _arguments \
   '(--dir)--dir[List of additional directories containing test suites]' \
   '(--suite)--suite[List of test suites to run]' \
   '(--group)--group[List of test groups to run]' \
   '(--case)--case[List of test cases to run]' \
   '(--label)--label[Test label]' \
   '(--config)--config[List of config files]' \
   '(--spec)--spec[List of test specifications]' \
   '(--join_specs)--join_specs[Merge all test specifications and perform a single test run]' \
   '(--allow_user_terms)--allow_user_terms[Allow user defined config values in config files]' \
   '(--logdir)--logdir[Log folder]' \
   '(--logopts)--logopts[Options for common test logging]' \
   '(--verbosity)--verbosity[Verbosity]' \
   '(-c --cover)'{-c,--cover}'[Generate cover data]' \
   '(--cover_export_name)--cover_export_name[Base name of the coverdata file to write]' \
   '(--repeat)--repeat[How often to repeat tests]' \
   '(--duration)--duration[Max runtime \(format: HHMMSS\)]' \
   '(--until)--until[Run until \(format: HHMMSS\)]' \
   '(--force_stop)--force_stop[Force stop on test timeout \(true | false | skip_rest\)]' \
   '(--basic_html)--basic_html[Show basic HTML]' \
   '(--stylesheet)--stylesheet[CSS stylesheet to apply to html output]' \
   '(--decrypt_key)--decrypt_key[Path to key for decrypting config]' \
   '(--decrypt_file)--decrypt_file[Path to file containing key for decrypting config]' \
   '(--abort_if_missing_suites)--abort_if_missing_suites[Abort if suites are missing]' \
   '(--multiply_timetraps)--multiply_timetraps[]' \
   '(--scale_timetraps)--scale_timetraps[Scale timetraps]' \
   '(--create_priv_dir)--create_priv_dir[Create priv dir \(auto_per_run | auto_per_tc | manual_per_tc\)]' \
   '(--include)--include[Directories containing additional include files]' \
   '(--readable)--readable[Shows test case names and only displays logs to shell on failures \(true | compact | false\)]' \
   '(-v --verbose)'{-v,--verbose}'[Verbose output]' \
   '(--name)--name[Gives a long name to the node]' \
   '(--sname)--sname[Gives a short name to the node]' \
   '(--setcookie)--setcookie[Sets the cookie if the node is distributed]' \
   '(--sys_config)--sys_config[List of application config files]' \
   '(--compile_only)--compile_only[Compile modules in the project with the test configuration but do not run the tests]' \
   '(--retry)--retry[Experimental feature. If any specification for previously failing test is found, runs them.]' \
   '(--fail_fast)--fail_fast[Experimental feature. If any test fails, the run is aborted. Since common test does not support this natively, we abort the rebar3 run on a failure. This May break CT''s disk logging and other rebar3 features.]' \


}

function _rebar3_clean {
  local -a commands

  _arguments \
   '(-a --all)'{-a,--all}'[Clean all apps include deps]' \
   '(--apps)--apps[Clean a specific list of apps or dependencies]' \
   '(-p --profile)'{-p,--profile}'[Clean under profile. Equivalent to `rebar3 as <profile> clean`]' \


}

function _rebar3_as {
  local -a commands

  _arguments \
   '1:Profiles to run as.:' \
   "1: :->cmnds" \
   "*::arg:->args"

  case $state in
  cmnds)
    commands=(
      "test:"
    )
    _describe "command" commands
    ;;
  esac

  case "$words[1]" in
  test)
    _rebar3_as_test
    ;;
  esac
}

function _rebar3_as_test {
  local -a commands

   _message 'no more arguments'


}


compdef _rebar3 rebar3
