# most use variables
sdk_home="$HOME"/sdk
data_home="$HOME"/.local/share
config_home="$HOME"/.config
cache_home="$HOME"/.cache

# for zsh self
export ZDOTDIR="$HOME"/.config/zsh
export HISTFILE="$cache_home"/zsh_history
export CLICOLOR=true
export LSCOLORS="exfxcxdxbxegedabagacad"
export XDG_STATE_HOME="$HOME"/.local/state
export XMAKE_GLOBALDIR="$sdk_home/xmake"
export PSQLRC="$config_home/psqlrc"
export PSQL_HISTORY="$XDG_STATE_HOME/psql/history"
export NPM_CONFIG_USERCONFIG="$config_home/npm/npmrc"
export NODE_REPL_HISTORY="$XDG_STATE_HOME/npm/history"
export NODE_PATH="/opt/homebrew/lib/node_modules:$data_home/npm/lib/node_modules/"

# for less
export LESSKEY="$config_home/less/lesskey"
export LESSHISTFILE="$XDG_STATE_HOME/less/history"

# for perl
export PERL_MB_OPT="--install_base '$sdk_home/perl5'"
export PERL_MM_OPT="INSTALL_BASE=$sdk_home/perl5"
export PERL_LOCAL_LIB_ROOT="$sdk_home/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"
export PERL5LIB="$sdk_home/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"
export MANPATH="$MANPATH":"$sdk_home/texlive/texmf-dist/doc/man"
export INFOPATH="INFOPATH":"$sdk_home/texlive/texmf-dist/doc/info"

# for python
export JUPYTER_DATA_DIR="$config_home/jupyter"
export IPYTHONDIR="$JUPYTER_DATA_DIR"
export JUPYTER_CONFIG_DIR="$JUPYTER_DATA_DIR"
export WORKON_HOME="$sdk_home/virtualenvs"
export PYTHONSTARTUP="$config_home/pip/pyrc"
export PYLINTHOME="$XDG_STATE_HOME/pylint"
export CONDARC="~/.conda/condarc"
export MPLCONFIGDIR="$config_home/matplotlib"

# for rust
export RUSTUP_HOME="$sdk_home"/rustup
export CARGO_HOME="$sdk_home"/cargo

# for haskell
export GHCUP_USE_XDG_DIRS=true
export CABAL_CONFIG="$config_home"/cabal/config
export CABAL_DIR="$sdk_home"/cabal
export AGDA_DIR="$config_home"/cabal/agda

# compose path
all_path="$RUSTUP_HOME/bin"                         # for rustup
all_path+=":$CARGO_HOME/bin"                        # for rust cargo
all_path+=":$HOME/.local/bin"                       # user binary
all_path+=":$data_home/npm/bin"                     # node/npm
all_path+=":$CABAL_DIR/bin"                         # haskell cabal
all_path+=":$sdk_home/perl5/bin"                    # perl
all_path+=":$sdk_home/texlive/bin/universal-darwin" # texlive
all_path+=":/opt/homebrew/opt/postgresql@16/bin"    # postgres
export PATH="$PATH":"$all_path":

# for proxy
export https_proxy=http://127.0.0.1:49580
export http_proxy=$https_proxy
export all_proxy=$https_proxy
