#!/usr/bin/env zsh

# most use variables
declare -lA paths
paths[sdk]="$HOME/.local/sdk"
paths[data]="$HOME/.local/share"
paths[config]="$HOME/.config"
paths[cache]="$HOME/.cache"
export XDG_USER_BIN="$HOME/.local/bin"
export XDG_CACHE_HOME="${paths[cache]}"
export XDG_CONFIG_HOME="${paths[config]}"
export XDG_STATE_HOME="$HOME/.local/state"
export EDITOR=hx
export VISUAL=hx

# zsh
export ZDOTDIR="${paths[config]}/zsh"
export HISTFILE="$XDG_STATE_HOME/zsh_history"
export CLICOLOR=true
export LSCOLORS="exfxcxdxbxegedabagacad"

# homebrew
export HOMEBREW_PREFIX="/opt/homebrew"
export HOMEBREW_CELLAR="$HOMEBREW_PREFIX/Cellar"
export HOMEBREW_REPOSITORY="$HOMEBREW_PREFIX"

# utils
export MANPATH="/usr/share/man:/usr/local/share/man"
export MANPATH="$MANPATH:$HOMEBREW_PREFIX/share/man"
export INFOPATH="$HOMEBREW_PREFIX/share/info"
export LESSKEY="${paths[config]}/less/lesskey"
export LESSHISTFILE="$XDG_STATE_HOME/less_history"
export RLWRAP_HOME="$XDG_STATE_HOME/rlwrap_history"
export GNUPGHOME="$HOME/.local/share/gnupg"
export SQLITE_HISTORY="$XDG_STATE_HOME/sqlite_history"
export PSQL_HISTORY="$XDG_STATE_HOME/psql_history"

# rust
export RUSTUP_BIN="$HOMEBREW_PREFIX/opt/rustup/bin"
export RUSTUP_HOME="${paths[sdk]}/rustup"
export CARGO_HOME="${paths[sdk]}/cargo"
export RUST_BACKTRACE=full
# deno
export DENO_DIR="$XDG_STATE_HOME/deno"
export DENO_INSTALL="${paths[sdk]}/deno"
export DENO_INSTALL_ROOT="${paths[sdk]}/deno"
export DENO_REPL_HISTORY="$DENO_DIR/history.txt"
export DENO_NO_UPDATE_CHECK=true
export npm_config_cache="${paths[cache]}/npm"
# python
export UV_PYTHON_PREFERENCE="only-managed"
export JUPYTER_DATA_DIR="${paths[config]}/jupyter"
export IPYTHONDIR="$JUPYTER_DATA_DIR"
export JUPYTER_CONFIG_DIR="$JUPYTER_DATA_DIR"
export PYTHONSTARTUP="${paths[config]}/pip/startup.py"
export MPLCONFIGDIR="$XDG_STATE_HOME/matplotlib"
#? irb
export IRBRC="${paths[config]}/irbrc"
#? java
export JAVA_VERSION="25.0.2+10"
export JAVA_HOME="${paths[sdk]}/jdk/jdk-$JAVA_VERSION/Contents/Home"
#? node
export NPM_CONFIG_USERCONFIG="${paths[config]}/npmrc"
export NODE_REPL_HISTORY="$XDG_STATE_HOME/npm_history"
export DSH_HOME="${paths[sdk]}/dsh/runtime"

# path
paths[homebrew]="/opt/homebrew/bin:/opt/homebrew/sbin" # homebrew
paths[path]="$XDG_USER_BIN"                            # user
paths[path]+=":$HOMEBREW_PREFIX/opt/llvm/bin"          # llvm
paths[path]+=":$RUSTUP_BIN"                            # rustup
paths[path]+=":$CARGO_HOME/bin"                        # cargo
paths[path]+=":$DENO_INSTALL_ROOT/bin"                 # deno
paths[path]+=":$JAVA_HOME/bin"                         # java
