# most use variables
declare -lA paths
paths[sdk]="$HOME/.local/sdk"
paths[data]="$HOME/.local/share"
paths[config]="$HOME/.config"
paths[cache]="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_USER_BIN="$HOME/.local/bin"
export EDITOR=nano
export VISUAL=nano

# for zsh self
export ZDOTDIR="${paths[config]}/zsh"
export HISTFILE="$XDG_STATE_HOME/zsh_history"
export CLICOLOR=true
export LSCOLORS="exfxcxdxbxegedabagacad"

# for utils
export HOMEBREW_PREFIX="/opt/homebrew"
export HOMEBREW_CELLAR="$HOMEBREW_PREFIX/Cellar"
export HOMEBREW_REPOSITORY="$HOMEBREW_PREFIX"
export MANPATH="/usr/share/man:/usr/local/share/man"
export MANPATH="$MANPATH:$HOMEBREW_PREFIX/share/man"
export INFOPATH="/usr/share/info:/usr/local/share/info"
export INFOPATH="$INFOPATH:$HOMEBREW_PREFIX/share/info"

# for less
export LESSKEY="${paths[config]}/less/lesskey"
export LESSHISTFILE="$XDG_STATE_HOME/less_history"
export RLWRAP_HOME="$XDG_STATE_HOME/rlwrap_history"
export GNUPGHOME="$HOME/.local/share/gnupg"

# for sql
export SQLITE_HISTORY="$XDG_STATE_HOME/sqlite_history"
export PSQLRC="${paths[config]}/psqlrc"
export PSQL_HISTORY="$XDG_STATE_HOME/psql_history"
export PGPASSFILE="$XDG_CONFIG_HOME/postgres/pgpass"
export PGSERVICEFILE="$XDG_CONFIG_HOME/postgres/pg_service.conf"

# for rust
export RUSTUP_BIN="$HOMEBREW_PREFIX/opt/rustup/bin" # homebrew only
export RUSTUP_HOME="${paths[sdk]}/rustup"
export CARGO_HOME="${paths[sdk]}/cargo"
export RUST_BACKTRACE=full

# for nodejs
export NPM_CONFIG_USERCONFIG="${paths[config]}/npmrc"
export NODE_REPL_HISTORY="$XDG_STATE_HOME/node_repl_history"
export NODE_PATH="$HOMEBREW_PREFIX/lib/node_modules:$XDG_DATA_HOME/npm/lib/node_modules"

# for python
export JUPYTER_DATA_DIR="${paths[config]}/jupyter"
export IPYTHONDIR="$JUPYTER_DATA_DIR"
export JUPYTER_CONFIG_DIR="$JUPYTER_DATA_DIR"
export PYTHONSTARTUP="${paths[config]}/pip/startup.py"
export MPLCONFIGDIR="$XDG_STATE_HOME/matplotlib"

#? uv
export UV_PYTHON_PREFERENCE="only-managed"
#? java
export JAVA_VERSION="25.0.2+10"
export JAVA_HOME="${paths[sdk]}/jdk/jdk-$JAVA_VERSION/Contents/Home"
export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=$XDG_STATE_HOME/java -Djavafx.cachedir=$XDG_STATE_HOME/java/openjfx"
#? lean
export ELAN_HOME="${paths[sdk]}/elan"

# compose path
paths[homebrew]="/opt/homebrew/bin:/opt/homebrew/sbin" # for homebrew
paths[path]=":$XDG_USER_BIN"                           # for user local
paths[path]+=":$HOMEBREW_PREFIX/opt/llvm/bin"          # for llvm
paths[path]+=":$RUSTUP_BIN"                            # for rustup itself
paths[path]+=":$CARGO_HOME/bin"                        # for rust cargo
paths[path]+=":$HOME/.local/share/npm/bin"             # for nodejs
paths[path]+=":$JAVA_HOME/bin"                         # for java
paths[path]+=":$ELAN_HOME/bin"                         # for lean
export PATH="${paths[path]}":"$PATH"                   # user path before system path
