# for zsh
autoload -Uz compinit
compinit
zstyle ':completion:*' menu select cache-path "$HOME/.cache/zsh"
autoload -Uz promptinit
promptinit
prompt walters

# for brew
export GPG_TTY=$(tty)
export GNUPGHOME="$HOME"/.local/share/gnupg
eval "$(/opt/homebrew/bin/brew shellenv)"

if command -v pandoc >/dev/null 2>&1; then
  cv2pdf() {
    local ftype="$1"
    shift
    local fname="$1"
    shift
    local oname="${fname%.*}.pdf"
    pandoc -f "$ftype" -t "pdf" "$fname" \
      -o "$oname" \
      --pdf-engine=lualatex \
      --metadata-file="$HOME/projects/config.d/others/pmeta.yaml"
  }
fi

# daily update
dailyup() {
  brew update
  brew upgrade
  ## texlive
  if command -v tlmgr >/dev/null 2>&1; then
    tlmgr update --all --self --reinstall-forcibly-removed
  fi
  ## conda
  if command -v conda >/dev/null 2>&1; then
    conda update --all --yes
  fi
  ## rust
  if command -v rustup >/dev/null 2>&1; then
    rustup update
    if [ "$?" = '0' ]; then
      cargo install --force --all-features \
        mdbook \
        nu \
        starship
    fi
  fi
  echo "should update cargo & ghcup by hand"
}

# activate conda
eval "$(~/sdk/conda/bin/conda "shell.$(basename "${SHELL}")" hook)"
if conda env list | grep dev >/dev/null 2>&1; then
  conda activate dev
fi

# yt-dlp wrapper
if command -v "yt-dlp" >/dev/null 2>&1; then
  yd() {
    local url="$1"
    shift
    if [ -z "$url" ]; then
      echo "please give a url"
      return 1
    fi
    yt-dlp -o "%(uploader_id)s/%(playlist_title)s/p%(playlist_index)03d-%(title)s.%(ext)s" \
      -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' \
      "$url" \
      "$@"
    return 0
  }
fi
