# for zsh
autoload -Uz compinit
compinit
zstyle ':completion:*' menu select cache-path "$HOME/.cache/zsh"
autoload -Uz promptinit
promptinit
prompt walters

# for brew
export GPG_TTY=$(tty)
export GNUPGHOME="$HOME"/.local/share/gnupg
eval "$(/opt/homebrew/bin/brew shellenv)"

# yt-dlp wrapper
if command -v yt-dlp >/dev/null 2>&1; then
  yd() {
    local url="$1"
    shift
    if [ -z "$url" ]; then
      echo "please give a url"
      return 1
    fi
    yt-dlp -o "%(uploader_id)s/%(playlist_title)s/p%(playlist_index)03d-%(title)s.%(ext)s" \
      -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' \
      "$url" \
      "$@"
    return 0
  }
fi

# pandoc wrapper
if command -v pandoc >/dev/null 2>&1; then
  md2pdf() {
    local fromType="$1"
    shift
    local fileName="$1"
    shift
    local outputName="${fileName%.*}.pdf"
    pandoc -f "$fromType" -t "pdf" \
      "$fileName" \
      -o "$outputName" \
      --pdf-engine=lualatex \
      --metadata-file="$HOME/projects/config.d/others/pandoc-meta"
  }
fi
