[Resolve]
# use cf dns and google dns as main dns
DNS=1.1.1.2#security.cloudflare-dns.com 1.0.0.2#security.cloudflare-dns.com 8.8.8.8#dns.google 8.8.4.4#dns.google
# use ali dns as fallback
FallbackDNS=223.5.5.5#dns.alidns.com 223.6.6.6#dns.alidns.com
Domains=~.
DNSSEC=true
# try use DoT by default
DNSOverTLS=yes
# use systemd-resolved for mDNS
MulticastDNS=yes
LLMNR=yes
Cache=no-negative
CacheFromLocalhost=yes
DNSStubListener=yes
#DNSStubListenerExtra=
ReadEtcHosts=yes
ResolveUnicastSingleLabel=yes
StaleRetentionSec=2
