[Resolve]
# use ali dns as main dns
DNS=223.5.5.5#dns.alidns.com 2400:3200::1 223.6.6.6#dns.alidns.com 2400:3200:baba::1
# use cf dns and quad9 dns as fallback dns
FallbackDNS=1.1.1.2#security.cloudflare-dns.com 9.9.9.11#dns11.quad9.net
Domains=~.
DNSSEC=true
# try use DoT by default
DNSOverTLS=yes
# use systemd-resolved for mDNS
MulticastDNS=yes
LLMNR=yes
Cache=no-negative
CacheFromLocalhost=yes
DNSStubListener=yes
#DNSStubListenerExtra=
ReadEtcHosts=yes
ResolveUnicastSingleLabel=yes
StaleRetentionSec=2
