[Resolve]
# use cf dns and google dns as main dns
DNS=1.1.1.1 2606:4700:4700::1111 1.0.0.1 2606:4700:4700::1001 8.8.8.8 2001:4860:4860::8888 8.8.4.4 2001:4860:4860::8844
# use ali dns as fallback
FallbackDNS=223.5.5.5 2400:3200::1 223.6.6.6 2400:3200:baba::1
Domains=~.
DNSSEC=allow-downgrade
# use DoT by default
#DNSOverTLS=opportunistic
DNSOverTLS=yes
# use Avahi for mDNS
MulticastDNS=no
LLMNR=resolve
Cache=no-negative
CacheFromLocalhost=no
DNSStubListener=yes
#DNSStubListenerExtra=
ReadEtcHosts=yes
ResolveUnicastSingleLabel=yes
StaleRetentionSec=2
