[user]
	name = github-username
	email = email-for-gpg
	signingkey = path-to-ssh-pub-key-file
[commit]
	gpgsign = true
[color]
	ui = auto
[credential]
	helper = store
[core]
	editor = hx # use your editor
[init]
	defaultBranch = repo-src # use your repo name
[push]
	autoSetupRemote = true
[gpg]
	format = ssh
[gpg "ssh"]
	allowedSignersFile = path-to-ssh-allowed-signers-file
