# Configuration file for NetworkManager.
# See "man 5 NetworkManager.conf" for details.
[main]
auth-polkit=yes
dhcp=internal
hostname-mode=default
dns=systemd-resolved
rc-manager=symlink
systemd-resolved=yes
firewall-backend=iptables

[connection]
down-on-poweroff=yes
llmnr=yes
mdns=yes
dns-over-tls=yes
