#!/usr/bin/env bash

# mysql history
export MYSQL_HISTFILE="$XDG_STATE_HOME"/mysql_history

# path
allPath="$HOME/.local/bin"               # user bin
allPath+=":$HOME/.local/share/npm/bin"   # node
allPath+=":$HOME/.local/share/cabal/bin" # haskell
allPath+=":$HOME/.local/share/cargo/bin" # rust
allPath+=":$HOME/.local/share/go/bin"    # golang
allPath+=":$PATH"
export PATH="$allPath"

# ghcup-env
[ -f "/home/kands/.local/share/ghcup/env" ] && source "/home/kands/.local/share/ghcup/env"

systemctl --user import-environment PATH
