#? haskell
export integer STACK_XDG=1
export integer GHCUP_USE_XDG_DIRS=1
export CABAL_DIR="${paths[data]}/cabal"
export CABAL_CONFIG="${paths[config]}/cabal/config"
export AGDA_DIR="${paths[sdk]}/agda"
#? lean
export ELAN_HOME="${paths[sdk]}/elan"
#? ocaml
export OPAMROOT="${paths[sdk]}/opam"
#? nodejs
export NPM_CONFIG_USERCONFIG="$paths[config]/npmrc"
export NODE_REPL_HISTORY="$XDG_STATE_HOME/npm_history"
export NODE_PATH="/opt/homebrew/lib/node_modules:$paths[data]/npm/lib/node_modules/"
#? mysql
export MYSQL_HISTFILE="$XDG_STATE_HOME/mysql_history"
#? latex
export TEXMFHOME="$paths[data]/texmf"
export TEXMFVAR="$paths[cache]/texlive/texmf-var"
export TEXMFCONFIG="$paths[config]/texlive/texmf-config"
#? elixir
export MIX_HOME="$paths[sdk]/elixir/mix"
export MIX_ARCHIVES="$MIX_HOME/archives"
export HEX_HOME="$paths[sdk]/elixir/hex"
#? go
export GOPATH="$XDG_STATE_HOME/go"
export GOMODCACHE="$GOPATH/pkg/mod"
export GOPROXY="https://proxy.golang.org,direct"
#? ruby
export BUNDLE_PATH="$paths[sdk]/ruby/gem"
export BUNDLE_USER_HOME="$paths[sdk]/ruby/bundle"
export BUNDLE_USER_CACHE="$BUNDLE_USER_HOME/cache"
export BUNDLE_USER_CONFIG="$BUNDLE_USER_HOME/config"
export BUNDLE_USER_PLUGIN="$BUNDLE_USER_HOME/plugin"
export SOLARGRAPH_CACHE="$paths[cache]/solargraph"
export TRAVIS_CONFIG_PATH="$paths[config]/travis"
#? dotnet
export DOTNET_ROOT="$HOME/.dotnet/sdk"
export DOTNET_CLI_HOME="$HOME/.dotnet/caches"
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export DOTNET_GENERATE_ASPNET_CERTIFICATE=0
export NUGET_PACKAGES="$paths[data]/NuGet/packages"
export NUGET_HTTP_CACHE_PATH="$paths[data]/NuGet/v3-cache"
