# for rust
CARGO_HOME="$XDG_SDK_HOME/cargo"
RUSTUP_HOME="$XDG_SDK_HOME/rustup"
RUST_BACKTRACE=full
# for nodejs
NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npmrc"
NODE_REPL_HISTORY="$XDG_STATE_HOME/node_repl_history"
NODE_PATH="/usr/lib/node_modules:$XDG_DATA_HOME/npm/lib/node_modules"
# for python
JUPYTER_DATA_DIR="$XDG_CONFIG_HOME/jupyter"
IPYTHONDIR="$JUPYTER_DATA_DIR"
JUPYTER_CONFIG_DIR="$JUPYTER_DATA_DIR"
PYTHONSTARTUP="$XDG_CONFIG_HOME/pip/startup.py"
MPLCONFIGDIR="$XDG_STATE_HOME/matplotlib"

#? rye
RYE_HOME="$XDG_SDK_HOME/rye"
#? sage config
DOT_SAGE="$XDG_STATE_HOME/sagemath"
SAGE_LOCAL="$XDG_SDK_HOME/sagemath"
SAGE_ROOT="$XDG_SDK_HOME/sagemath/sage"
#? haskell
STACK_XDG=1
GHCUP_USE_XDG_DIRS=1
CABAL_DIR="$XDG_DATA_HOME/cabal"
CABAL_CONFIG="$XDG_CONFIG_HOME/cabal/config"
AGDA_DIR="$XDG_SDK_HOME/agda"
#? java
JAVA_VERSION="21.0.6+7"
JAVA_HOME="$XDG_SDK_HOME/jdk/jdk-$JAVA_VERSION"
#? go
GOPATH="$XDG_STATE_HOME/go"
GOMODCACHE="$GOPATH/pkg/mod"
GOPROXY="https://proxy.golang.org,direct"
