# for rust
CARGO_HOME="$XDG_SDK_HOME/cargo"
RUSTUP_HOME="$XDG_SDK_HOME/rustup"
RUST_BACKTRACE=full
# for nodejs
NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npmrc"
NODE_REPL_HISTORY="$XDG_STATE_HOME/node_repl_history"
NODE_PATH="/usr/lib/node_modules:$XDG_DATA_HOME/npm/lib/node_modules"
# for python
JUPYTER_DATA_DIR="$XDG_CONFIG_HOME/jupyter"
IPYTHONDIR="$JUPYTER_DATA_DIR"
JUPYTER_CONFIG_DIR="$JUPYTER_DATA_DIR"
PYTHONSTARTUP="$XDG_CONFIG_HOME/pip/startup.py"
MPLCONFIGDIR="$XDG_STATE_HOME/matplotlib"

#? uv
UV_PYTHON_PREFERENCE="only-managed"
#? lean
ELAN_HOME="$XDG_SDK_HOME/elan"
#? java
JAVA_VERSION="21.0.8+9"
JAVA_HOME="$XDG_SDK_HOME/jdk/jdk-$JAVA_VERSION"
