#!/bin/env bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls="ls --color=auto"
alias ww="fastfetch"

# GPG config
export GPG_TTY=$(tty)
export GNUPGHOME="$XDG_DATA_HOME/gnupg"

# java config
export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=$XDG_STATE_HOME/java -Djavafx.cachedir=$XDG_STATE_HOME/openjfx"

# daily update
function dailyup() {
  # paru
  paru -Syu
  paru -Fy
  paru -Sc
  # rust
  if command -v rustup >/dev/null 2>&1; then
    if rustup update; then
      cargo install --all-features \
        mdbook \
        hyperfine
      cargo install --features lsp --locked taplo-cli
      cargo install --git https://github.com/Myriad-Dreamin/tinymist --locked tinymist-cli
    fi
  fi
}

# PS1='[\u@\h \W]\$ '

# self prompt
function exitstatus() {
  if [[ "$?" == '0' ]]; then
    printf '\033[1;32m[v]\033[0m'
  else
    printf '\033[1;31m[x]\033[0m'
  fi
}

function usersymbol() {
  if [[ "$UID" == '0' ]]; then
    printf '\033[1;31m[#]\033[0m'
  else
    printf '\033[1;36m[$]\033[0m'
  fi
}

export PS0='\[\033[0;36m\]Out[\#]:= \[\033[0m\]\n'
export PS1='[\u@\h \w \A]-\[$(exitstatus)\]-\[$(usersymbol)\]\n\[\033[0;33m\]In[\#]:= \[\033[0m\]'
export PS2=' ~> '

# python venv
if command -v python3 >/dev/null 2>&1; then
  function create-venv() {
    if [[ -n "$1" ]]; then
      vname="$1"
    else
      vname="$(basename "$PWD")"
    fi
    python3 -m venv .venv --prompt "$vname"
  }

  function activate-venv() {
    local dname=".venv"
    if [[ -n "$1" ]]; then
      dname="$1"
    fi
    if [[ -d "$PWD/$dname" ]] && [[ -f "$PWD/$dname/bin/activate" ]]; then
      source "$PWD/$dname/bin/activate"
    fi
  }
fi

# typst preview
if command -v tinymist >/dev/null 2>&1; then
  function typre() {
    case "$2" in
    s | slide)
      previewMode="slide"
      ;;
    *)
      previewMode="document"
      ;;
    esac
    tinymist preview "$1" --data-plane-host=localhost:23635 \
      --invert-colors=auto \
      --partial-rendering=true \
      --refresh-style=on-save \
      --preview-mode="$previewMode"
  }
fi

# video convert
if command -v ffmpeg >/dev/null 2>&1; then
  # convert to mp4
  function conv2mp4() {
    local filename="$1"
    local basename="${filename%.*}"
    ffmpeg -i "$filename" \
      -crf 16 -c:a aac -b:a 192k \
      -vf "pad=ceil(iw/2)*2:ceil(ih/2)*2" \
      -y "$basename.mp4"
  }
  # aria2c wrapper
  function a2c() {
    if command -v aria2c >/dev/null 2>&1; then
      aria2c --max-connection-per-server=4 \
        --min-split-size=5M \
        --continue \
        "$@"
    fi
  }
  # yt-dlp wrapper
  function yd() {
    if command -v yt-dlp >/dev/null 2>&1; then
      local url="$1"
      local browser="$2"
      if [ -z "$url" ] || [ -z "$browser" ]; then
        echo "usage: yd <url> <browser> [yt-dlp arguments...]"
        return 1
      fi
      shift 2
      yt-dlp -o "%(uploader_id)s/%(playlist_title)s/p%(playlist_index)03d-%(title)s.%(ext)s" \
        -f "bv*[vcodec^=avc1]+ba[acodec^=mp4a]/bv*[vcodec^=avc1]+ba/b" \
        --remux-video mp4 \
        --download-archive archive.txt \
        --ignore-errors \
        --retry-sleep http:16 \
        --sleep-requests 4 \
        --sleep-interval 8 \
        --max-sleep-interval 16 \
        --sleep-subtitles 16 \
        --write-auto-subs \
        --sub-format="vtt" \
        --sub-langs="en-orig,en,en-US,zh-Hans,zh-CN" \
        --embed-subs \
        --js-runtimes deno \
        --remote-components ejs:github \
        --cookies-from-browser="$browser" \
        "$url" \
        "$@"
      return 0
    fi
  }
fi
