#!/bin/env bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls="ls --color=auto"
alias ww="fastfetch"

# GPG config
export GPG_TTY=$(tty)
export GNUPGHOME="$XDG_DATA_HOME/gnupg"

# java config
export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=$XDG_STATE_HOME/java -Djavafx.cachedir=$XDG_STATE_HOME/openjfx"

# daily update
function dailyup() {
  # paru
  paru -Syu
  paru -Fy
  paru -Sc
  # rust
  if command -v rustup >/dev/null 2>&1; then
    if rustup update; then
      cargo install --all-features \
        mdbook \
        hyperfine \
        sqlx-cli
    fi
  fi
}

# PS1='[\u@\h \W]\$ '

# self prompt
function exitstatus() {
  if [[ "$?" == '0' ]]; then
    printf '\033[1;32m[v]\033[0m'
  else
    printf '\033[1;31m[x]\033[0m'
  fi
}

function usersymbol() {
  if [[ "$UID" == '0' ]]; then
    printf '\033[1;31m[#]\033[0m'
  else
    printf '\033[1;36m[$]\033[0m'
  fi
}

export PS0='\[\033[0;36m\]Out[\#]:= \[\033[0m\]\n'
export PS1='[\u@\h \w \A]-\[$(exitstatus)\]-\[$(usersymbol)\]\n\[\033[0;33m\]In[\#]:= \[\033[0m\]'
export PS2=' ~> '

# python venv
if command -v python3 >/dev/null 2>&1; then
  function create-venv() {
    local vname="$(basename "$PWD")"
    if [[ -n "$1" ]]; then
      vname="$1"
    fi
    python3 -m venv .venv --prompt "$vname"
  }
  function activate-venv() {
    local dname=".venv"
    if [[ -n "$1" ]]; then
      dname="$1"
    fi
    if [[ -d "$PWD/$dname" ]] && [[ -f "$PWD/$dname/bin/activate" ]]; then
      source "$PWD/$dname/bin/activate"
    fi
  }
fi

# active opam env
[[ ! -r "$OPAMROOT/opam-init/init.sh" ]] || source "$OPAMROOT/opam-init/init.sh" >/dev/null 2>/dev/null

# video convert
if command -v ffmpeg >/dev/null 2>&1; then
  # convert to mp4
  function conv2mp4() {
    local filename="$1"
    local basename="${filename%.*}"
    ffmpeg -i "$filename" \
      -vf "pad=ceil(iw/2)*2:ceil(ih/2)*2" \
      -y -an -crf 0 \
      "$basename.mp4"
  }
  # aria2c wrapper
  function a2c() {
    if command -v aria2c >/dev/null 2>&1; then
      aria2c --max-connection-per-server=4 \
        --min-split-size=5M \
        --continue \
        "$@"
    fi
  }
  # yt-dlp wrapper
  function yd() {
    if command -v yt-dlp >/dev/null 2>&1; then
      local url="$1"
      shift 1
      local browser="$1"
      shift 1
      if [ -z "$url" ]; then
        echo "usage: yd [url] (...[yt-dlp arguments])"
        return 1
      fi
      yt-dlp -o "%(uploader_id)s/%(playlist_title)s/p%(playlist_index)03d-%(title)s.%(ext)s" \
        -f "bv*+ba/b" \
        --recode-video="mp4" \
        --write-auto-subs \
        --sub-format="vtt" \
        --sub-langs="en.*,zh-Hans" \
        --embed-subs \
        --js-runtimes node \
        --cookies-from-browser="$browser" \
        "$url" \
        "$@"
      return 0
    fi
  }
fi
