#!/usr/bin/env bash

# compose path
allPath="$XDG_USER_BIN"            # for user local
allPath+=":$CARGO_HOME/bin"        # for rust cargo
allPath+=":$DENO_INSTALL_ROOT/bin" # for deno
allPath+=":$JAVA_HOME/bin"         # for java
export PATH="$allPath":"$PATH"     # user path before system path

# try use en_US.UTF-8 as tty LANG
if [[ "$XDG_SESSION_TYPE" == "tty" ]]; then
  # systemd environment variables
  if [[ -f "/usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator" ]]; then
    export "$(/usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator)"
  fi
  export LANG='en_US.UTF-8'
  export LC_NUMERIC='en_US.UTF-8'
  export LC_TIME='en_US.UTF-8'
fi

# import path
systemctl --user import-environment PATH

# read bashrc if it exists
[[ -f "$HOME/.bashrc" ]] && source "$HOME/.bashrc"
